name: perf_list
description: "Listar qualquer coisa"
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  firebase_core: ^3.8.1  # Use the latest stable version
  cloud_firestore: ^5.5.1  # Use the latest stable version
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_auth: ^5.3.4
  firebase_auth_web: ^5.13.5
  intl: ^0.20.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  firebase_storage: ^12.3.7
  cloudinary_dart: ^0.0.11
  cloudinary_api: ^1.0.2
  cloudinary: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
